name: Deploy tedrust.com Website

on:
  push:
    branches: [ main ]
    paths:
      - 'Personal/tedrust.com/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
      working-directory: Personal/tedrust.com

    - name: Build
      run: npm run build
      working-directory: Personal/tedrust.com

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages-tedrust # Deploying to a separate branch
        folder: Personal/tedrust.com/build # Folder to deploy
